### ISSUE TITLE
Allow references outside of tidy modules

### ISSUE THREAD

**Issue by jneug** [Mc-Zen/tidy#39]
I think the catch-all implementation of references in Tidy 0.4.0 is a little too much, since it disallows references to labels outside Tidy modules. For example, references to section headings in the manual.

Here is a minimal example of what I mean. The reference `@sec:examples` in **utils.typ** gets changed to `@utils:sec:examples` and won't link to the heading in **manual.typ**.

**utils.typ**
```typst
/// Colorizes a test string with a color map.
/// See @sec:examples for usage examples.
/// -> content
#let colorize(
  /// The text string to colorize.
  /// -> str
  str,
  /// Color map to use for colorizing.
  /// -> array
  color-map: color.map.rainbow,
) = {
  let step = int(color-map.len() / str.len()) - 1
  str.split("").enumerate().map(((i, c)) => text(fill: color-map.at(i * step, default: color-map.at(-1)), c)).join("")
}
```

**lib.typ**
```typst
#import "utils.typ": colorize

#let rainbow = colorize
#let spectral = colorize.with(color-map: color.map.spectral)
```

**manual.typ**
````typst
#import "@local/tidy:0.4.0": show-module, parse-module

#import "lib.typ": *

= Package "colorize"

This package provides a set of `colorize` functions to colorize text.

== Module "utils"
#let m = parse-module(read("utils.typ"), name: "utils", label-prefix: "utils:")
#show-module(m)

== Examples <sec:examples>

== Rainbow example
```typ
#rainbow("Hello, World!")
```

#rainbow("Hello, World!")

== Spectral example
```typ
#spectral("Hello, World!")
```

#spectral("Hello, World!")
````

**Comment by Mc-Zen** [comment]
Ah, _that_ was exactly why I originally introduced the `@@` notation. 

But I got convinced that it's better not to have so much special syntax. 

Mmh...


Well, there are two things to consider:
1. Maybe the reference shouldn't be referring to the manual at all because the documentation should be able to stand on its own. That's at least one way to see it.  
  
  Maybe you want to move your example into the doc-comment!
  ````typ
  /// ...
  ///
  /// ```example
  /// #rainbow("Hello, World!")
  /// ```
  ````
  This would require you to add
  ```typ
  #let m = parse-module(read("utils.typ"), name: "utils", label-prefix: "utils:", scope: (rainbow: rainbow))
  ```
  or even `scope: dictionary(lib)` together with an `#import "lib.typ"` (without the asterisk `*`) to make all definitions is the lib available. 


2. You can use `label-prefix: ""` which should make it work **or** write `== Examples <utlils:sec:examples>` 😅
  Actually, the label prefix is just an option to allow a user to avoid potential clashes. Not sure if it is really necessary. Maybe the default should be just `""`



Another option that I see is for tidy to automatically check whether a label is undefined with the prefix added. If so, the prefix is just not added and the reference left as it is. I'm not sure if it is possible to check whether a label exists.

**Comment by jneug** [comment]
The minimal example was simplified to illustrate the issue. In a real-world scenario, the reference to another chapter of the manual would probably make more sense, like having a section about template creation that is referenced from utility functions required for template creation, or something like that.

I can see an argument for docstrings to be independent from the context they are rendered in, but it should be possible to filter out references that go to functions outside tidy modules. Don't you already keep a state of functions defined in the module? 

From a quick glance at the code, isn't it possible to just alter references to functions in the module and leave the rest alone. Something like this (I moved the call to `show-reference` inside the check, if `target` is a known function):

```typst
  #show ref: it => {
    let target = str(it.target)
    if target.starts-with(label-prefix) { return it }
    if not enable-cross-references {
      return raw(target)
    }
    let defs = def-state.final()
    if defs.at(target, default: none) == 1 {
      target += "()"
      (eval-scope.tidy.show-reference)(label(label-prefix + target), target)
    } else {
      it
    }
  }
```

I'm probably missing something, but I think there can be a solution that allows outside references for people that don't care about independent docstrings.

**Comment by Mc-Zen** [comment]
> The minimal example was simplified to illustrate the issue. In a real-world scenario, the reference to another chapter of the manual would probably make more sense, like having a section about template creation that is referenced from utility functions required for template creation, or something like that.

You're right, it might anyway be desirable to reference some tutorial section from the documentation in some cases. 

Good point, we can make use of the state. However some care is needed with cross-referencing function arguments which also fall under the category "not in the `def-state`".

**Comment by Mc-Zen** [comment]
Thanks for reporting this early! I think I might still be able to push this as a hotfix to tidy:0.4.0.
